# Q1

In [19]:
from sklearn.datasets import fetch_california_housing

df = fetch_california_housing(as_frame=True).frame
df

       MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  MedHouseVal
0      8.3252      41.0  6.984127  ...     37.88    -122.23        4.526
1      8.3014      21.0  6.238137  ...     37.86    -122.22        3.585
2      7.2574      52.0  8.288136  ...     37.85    -122.24        3.521
3      5.6431      52.0  5.817352  ...     37.85    -122.25        3.413
4      3.8462      52.0  6.281853  ...     37.85    -122.25        3.422
...       ...       ...       ...  ...       ...        ...          ...
20635  1.5603      25.0  5.045455  ...     39.48    -121.09        0.781
20636  2.5568      18.0  6.114035  ...     39.49    -121.21        0.771
20637  1.7000      17.0  5.205543  ...     39.43    -121.22        0.923
20638  1.8672      18.0  5.329513  ...     39.43    -121.32        0.847
20639  2.3886      16.0  5.254717  ...     39.37    -121.24        0.894

[20640 rows x 9 columns]

In [20]:
df.isnull().sum()

MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

In [21]:
X = df.drop('MedHouseVal', axis=1)
y = df['MedHouseVal']

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [30]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()

reg.fit(X_train_scaled, y_train)

LinearRegression()

In [31]:
from sklearn.metrics import r2_score, mean_absolute_error

y_pred = reg.predict(X_test_scaled)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"r^2 score = {r2}, Mean Absolute Error = {mae}")

r^2 score = 0.5757877060324511, Mean Absolute Error = 0.5332001304956565

In [32]:
i = 1
new_feat = X_test_scaled[i]
predicted = reg.predict([new_feat])
original = y_test.iloc[i]

print(f"Predicted = {predicted[0]}, Original = {original}")

Predicted = 1.7640165706624165, Original = 0.458

 # Q2

In [9]:
# i found this dataset on UCI ML website
from ucimlrepo import fetch_ucirepo 

# fetch dataset 
spambase = fetch_ucirepo(id=94) 
  
# data (as pandas dataframes) 
X = spambase.data.features 
y = spambase.data.targets 
  
X.isnull().sum()

word_freq_make                0
word_freq_address             0
word_freq_all                 0
word_freq_3d                  0
word_freq_our                 0
word_freq_over                0
word_freq_remove              0
word_freq_internet            0
word_freq_order               0
word_freq_mail                0
word_freq_receive             0
word_freq_will                0
word_freq_people              0
word_freq_report              0
word_freq_addresses           0
word_freq_free                0
word_freq_business            0
word_freq_email               0
word_freq_you                 0
word_freq_credit              0
word_freq_your                0
word_freq_font                0
word_freq_000                 0
word_freq_money               0
word_freq_hp                  0
word_freq_hpl                 0
word_freq_george              0
word_freq_650                 0
word_freq_lab                 0
word_freq_labs                0
word_freq_telnet              0
word_freq_857                 0
word_freq_data                0
word_freq_415                 0
word_freq_85                  0
word_freq_technology          0
word_freq_1999                0
word_freq_parts               0
word_freq_pm                  0
word_freq_direct              0
word_freq_cs                  0
word_freq_meeting             0
word_freq_original            0
word_freq_project             0
word_freq_re                  0
word_freq_edu                 0
word_freq_table               0
word_freq_conference          0
char_freq_;                   0
char_freq_(                   0
char_freq_[                   0
char_freq_!                   0
char_freq_$                   0
char_freq_#                   0
capital_run_length_average    0
capital_run_length_longest    0
capital_run_length_total      0
dtype: int64

In [10]:
X.dtypes # data is alr clean

word_freq_make                float64
word_freq_address             float64
word_freq_all                 float64
word_freq_3d                  float64
word_freq_our                 float64
word_freq_over                float64
word_freq_remove              float64
word_freq_internet            float64
word_freq_order               float64
word_freq_mail                float64
word_freq_receive             float64
word_freq_will                float64
word_freq_people              float64
word_freq_report              float64
word_freq_addresses           float64
word_freq_free                float64
word_freq_business            float64
word_freq_email               float64
word_freq_you                 float64
word_freq_credit              float64
word_freq_your                float64
word_freq_font                float64
word_freq_000                 float64
word_freq_money               float64
word_freq_hp                  float64
word_freq_hpl                 float64
word_freq_george              float64
word_freq_650                 float64
word_freq_lab                 float64
word_freq_labs                float64
word_freq_telnet              float64
word_freq_857                 float64
word_freq_data                float64
word_freq_415                 float64
word_freq_85                  float64
word_freq_technology          float64
word_freq_1999                float64
word_freq_parts               float64
word_freq_pm                  float64
word_freq_direct              float64
word_freq_cs                  float64
word_freq_meeting             float64
word_freq_original            float64
word_freq_project             float64
word_freq_re                  float64
word_freq_edu                 float64
word_freq_table               float64
word_freq_conference          float64
char_freq_;                   float64
char_freq_(                   float64
char_freq_[                   float64
char_freq_!                   float64
char_freq_$                   float64
char_freq_#                   float64
capital_run_length_average    float64
capital_run_length_longest      int64
capital_run_length_total        int64
dtype: object

In [11]:
X

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,word_freq_conference,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.0,0.000,0.000,0.0,0.778,0.000,0.000,3.756,61,278
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.0,0.000,0.132,0.0,0.372,0.180,0.048,5.114,101,1028
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.0,0.010,0.143,0.0,0.276,0.184,0.010,9.821,485,2259
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.0,0.000,0.137,0.0,0.137,0.000,0.000,3.537,40,191
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.0,0.000,0.135,0.0,0.135,0.000,0.000,3.537,40,191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4596,0.31,0.00,0.62,0.0,0.00,0.31,0.00,0.00,0.00,0.00,...,0.0,0.000,0.232,0.0,0.000,0.000,0.000,1.142,3,88
4597,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.000,0.000,0.0,0.353,0.000,0.000,1.555,4,14
4598,0.30,0.00,0.30,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.102,0.718,0.0,0.000,0.000,0.000,1.404,6,118
4599,0.96,0.00,0.00,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.0,0.000,0.057,0.0,0.000,0.000,0.000,1.147,5,78
4600,0.00,0.00,0.65,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.000,0.000,0.0,0.125,0.000,0.000,1.250,5,40

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [13]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_scaled, y_train)

/home/zaiyan/miniconda3/envs/simple_ml/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [14]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_pred = clf.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Accuracy = {accuracy}, Precision = {precision}, Recall = {recall}, f1 score = {f1}")

Accuracy = 0.9196525515743756, Precision = 0.9316939890710383, Recall = 0.8743589743589744, f1 score = 0.9021164021164021

In [19]:
i = 101

new_email = X_test_scaled[i]

predicted = clf.predict([new_email])

original = y_test.iloc[i]

print(f"Predicted = {'Spam' if predicted[0] else 'Not Spam'}, Original = {'Spam' if original.item() else 'Not Spam'}")

Predicted = Spam, Original = Spam

# Q3

In [48]:
import pandas as pd

df = pd.read_csv('online_retail_II.csv')

In [49]:
df.shape

(1067371, 8)

In [50]:
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [51]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [52]:
df.loc[df.duplicated(['Customer ID'])]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [56]:
df['Total Spending'] = df['Quantity'] * df['Price']

In [59]:
c_df = df.groupby('Customer ID').agg({
    'Total Spending' : 'sum',
    'Invoice': 'nunique',
    'Quantity': 'sum'
}).reset_index()

c_df

      Customer ID  Total Spending  Invoice  Quantity
0         12346.0          -64.68       17        52
1         12347.0         5633.32        8      3286
2         12348.0         2019.40        5      2714
3         12349.0         4404.54        5      1619
4         12350.0          334.40        1       197
...           ...             ...      ...       ...
5937      18283.0         2736.65       22      1733
5938      18284.0          436.68        2       493
5939      18285.0          427.00        1       145
5940      18286.0         1188.43        3       592
5941      18287.0         4177.89        8      3011

[5942 rows x 4 columns]

In [62]:
c_df.columns = ['Customer ID', 'TotalSpending', 'Visits', 'Frequency']
c_df

      Customer ID  TotalSpending  Visits  Frequency
0         12346.0         -64.68      17         52
1         12347.0        5633.32       8       3286
2         12348.0        2019.40       5       2714
3         12349.0        4404.54       5       1619
4         12350.0         334.40       1        197
...           ...            ...     ...        ...
5937      18283.0        2736.65      22       1733
5938      18284.0         436.68       2        493
5939      18285.0         427.00       1        145
5940      18286.0        1188.43       3        592
5941      18287.0        4177.89       8       3011

[5942 rows x 4 columns]

In [67]:
threshold = c_df['TotalSpending'].quantile(0.75)
c_df['is_high_val'] = c_df['TotalSpending'] > threshold.astype(int)

c_df

      Customer ID  TotalSpending  Visits  Frequency  is_high_val
0         12346.0         -64.68      17         52        False
1         12347.0        5633.32       8       3286         True
2         12348.0        2019.40       5       2714        False
3         12349.0        4404.54       5       1619         True
4         12350.0         334.40       1        197        False
...           ...            ...     ...        ...          ...
5937      18283.0        2736.65      22       1733         True
5938      18284.0         436.68       2        493        False
5939      18285.0         427.00       1        145        False
5940      18286.0        1188.43       3        592        False
5941      18287.0        4177.89       8       3011         True

[5942 rows x 5 columns]

In [76]:
X = c_df[['TotalSpending', 'Visits', 'Frequency']]
y = c_df['is_high_val']
X

      TotalSpending  Visits  Frequency
0            -64.68      17         52
1           5633.32       8       3286
2           2019.40       5       2714
3           4404.54       5       1619
4            334.40       1        197
...             ...     ...        ...
5937        2736.65      22       1733
5938         436.68       2        493
5939         427.00       1        145
5940        1188.43       3        592
5941        4177.89       8       3011

[5942 rows x 3 columns]

In [78]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [79]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_scaled, y_train)

LogisticRegression()

In [80]:
clf.score(X_test_scaled, y_test)

0.9722455845248108

In [86]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_pred = clf.predict(X_test_scaled)
acc = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Accuracy = {accuracy}, Precision = {precision}, Recall = {recall}, f1 score = {f1}")

Accuracy = 0.9196525515743756, Precision = 0.9769230769230769, Recall = 0.9039145907473309, f1 score = 0.9390018484288355

In [94]:
i = 66

test_instance = X_test_scaled[i]

prediction = clf.predict([test_instance])

original = y_test.iloc[i]

print(f"Prediction = {'High Value' if prediction else 'Low Value'}, Original = {'High Value' if original else 'Low Value'}")

Prediction = High Value, Original = High Value